title: jtd
description: a simple test for just the docs
theme: just-the-docs

url: https://Solarium-Networks.github.io/jtd

aux_links:
  Template Repository: https://github.com/Solarium-Networks.github.io/jtd
